from __future__ import annotations

"""PairObservation -- pair-level predictive calibration (mission section
9/10). SEPARATE from both the leg-level CalibrationObservation ledger
(schema.py/store.py) and the slate-level policy evidence stream
(parlay_certification_v2/evidence_store.py). This stream exists to answer
a pure RESEARCH question later ("does a frozen pair-state representation
improve chronological unseen joint calibration over the independence
baseline?") -- it is never read by policy.select_action_for_day and never
gates action (see calibration/support.py: joint_support is OBSERVE_ONLY).

Every settled, gradable candidate pair generated by the frozen pregame
process is admitted here, NOT only the one pair the policy selected that
day (mission section 10's own example: 80 frozen candidates -> up to 80
PairObservations, but exactly 1 policy evidence row). pair_id is
deterministic (built from the two legs' own exact-event identities, the
same identity scheme candidate_adapter.py already uses for
candidate_id) -- reproducible identically whether computed live pregame
or re-derived post-hoc for settlement, since candidate generation is a
pure function of that day's frozen archived predictive/market data.
"""

import hashlib
import json
from dataclasses import asdict, dataclass

SCHEMA_VERSION = "PAIR_OBSERVATION_V1"


def _hash(fields: dict) -> str:
    canonical = json.dumps(fields, sort_keys=True, default=str)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


@dataclass(frozen=True)
class PairObservation:
    observation_id: str
    slate_id: str
    pair_id: str

    leg_1_event_id: str
    leg_2_event_id: str

    same_game: bool
    same_team: bool

    market_pair_type: str   # e.g. "R|TB" (sorted leg targets)
    line_pair_type: str     # e.g. "R|OVER|0.5__TB|UNDER|1.5"
    state_bucket_pair: str
    price_bucket: str        # coarse combined-decimal-price bucket, for strata counts

    quoted_pair_price: float | None  # None for same-game (no real SGP quote -- see pairs.py convention)

    predicted_joint_probability: float
    predicted_independence_probability: float
    joint_residual: float  # always 0.0 today -- see module docstring (no non-independence joint model exists yet)

    counterexample_count: int
    counterexample_mass: float
    retained_world_count: int
    retained_probability_mass: float

    calibration_snapshot_id: str | None
    predictive_version: str
    policy_version: str

    decision_timestamp: str

    leg_1_result: int | None  # 1/0, None if ungraded
    leg_2_result: int | None
    both_win: bool | None

    actual_pair_return: float | None  # None when quoted_pair_price is None (same-game) or ungraded

    settlement_status: str  # "settled" | "ungraded"
    settlement_timestamp: str

    row_hash: str
    schema_version: str = SCHEMA_VERSION

    def as_dict(self) -> dict:
        return asdict(self)


def build_pair_id(leg_1_event_id: str, leg_2_event_id: str) -> str:
    """Deterministic, order-independent pair identity."""
    a, b = sorted([leg_1_event_id, leg_2_event_id])
    return _hash({"leg_1": a, "leg_2": b})


def build_pair_observation(
    *,
    slate_id: str,
    leg_1_event_id: str,
    leg_2_event_id: str,
    same_game: bool,
    same_team: bool,
    market_pair_type: str,
    line_pair_type: str,
    state_bucket_pair: str,
    price_bucket: str,
    quoted_pair_price: float | None,
    predicted_joint_probability: float,
    predicted_independence_probability: float,
    counterexample_count: int,
    counterexample_mass: float,
    retained_world_count: int,
    retained_probability_mass: float,
    calibration_snapshot_id: str | None,
    predictive_version: str,
    policy_version: str,
    decision_timestamp: str,
    leg_1_result: int | None,
    leg_2_result: int | None,
    settlement_status: str,
    settlement_timestamp: str,
) -> PairObservation:
    pair_id = build_pair_id(leg_1_event_id, leg_2_event_id)
    both_win = bool(leg_1_result) and bool(leg_2_result) if (leg_1_result is not None and leg_2_result is not None) else None
    actual_pair_return = None
    if quoted_pair_price is not None and both_win is not None:
        actual_pair_return = (float(quoted_pair_price) - 1.0) if both_win else -1.0

    identity_fields = {
        "slate_id": slate_id, "pair_id": pair_id,
        "quoted_pair_price": quoted_pair_price,
        "leg_1_result": leg_1_result, "leg_2_result": leg_2_result,
        "settlement_status": settlement_status,
    }
    observation_id = _hash(identity_fields)
    row_hash = _hash({**identity_fields, "predicted_joint_probability": predicted_joint_probability})

    return PairObservation(
        observation_id=observation_id,
        slate_id=slate_id,
        pair_id=pair_id,
        leg_1_event_id=leg_1_event_id,
        leg_2_event_id=leg_2_event_id,
        same_game=same_game,
        same_team=same_team,
        market_pair_type=market_pair_type,
        line_pair_type=line_pair_type,
        state_bucket_pair=state_bucket_pair,
        price_bucket=price_bucket,
        quoted_pair_price=quoted_pair_price,
        predicted_joint_probability=predicted_joint_probability,
        predicted_independence_probability=predicted_independence_probability,
        joint_residual=float(predicted_joint_probability - predicted_independence_probability),
        counterexample_count=counterexample_count,
        counterexample_mass=counterexample_mass,
        retained_world_count=retained_world_count,
        retained_probability_mass=retained_probability_mass,
        calibration_snapshot_id=calibration_snapshot_id,
        predictive_version=predictive_version,
        policy_version=policy_version,
        decision_timestamp=decision_timestamp,
        leg_1_result=leg_1_result,
        leg_2_result=leg_2_result,
        both_win=both_win,
        actual_pair_return=actual_pair_return,
        settlement_status=settlement_status,
        settlement_timestamp=settlement_timestamp,
        row_hash=row_hash,
    )
