from __future__ import annotations

from itertools import product
from typing import Any, Iterable

import pandas as pd

from .gating import StrategyConfig
from .simulation import SimulationResult, simulate_strategy


def build_default_shadow_strategies() -> list[StrategyConfig]:
    return [
        StrategyConfig(
            name="production_calibrated",
            probability_shrink_factor=0.75,
            ranking_mode="ev_adjusted",
            selection_mode="thompson_ev",
            min_ev=0.05,
            min_final_confidence=0.05,
            max_history_staleness_days=14,
            min_recency_factor=0.85,
            min_recommendation="consider",
            max_plays_per_player=1,
            max_plays_per_game=2,
            max_pts_plays=6,
            max_trb_plays=2,
            max_ast_plays=2,
            max_total_plays=10,
            non_pts_min_gap_percentile=0.90,
            sizing_method="tiered_probability",
            base_bet_fraction=0.010,
            small_bet_fraction=0.005,
            medium_bet_fraction=0.010,
            full_bet_fraction=0.015,
            max_bet_fraction=0.02,
            max_total_bet_fraction=0.06,
            edge_scale_start_percentile=0.75,
            edge_scale_span=0.25,
            edge_scale_lift=0.15,
            edge_scale_max_multiplier=1.25,
            target_thresholds={
                "PTS": {"consider_pct": 0.80, "strong_pct": 0.90, "elite_pct": 0.95},
                "TRB": {"consider_pct": 0.90, "strong_pct": 0.95, "elite_pct": 0.975},
                "AST": {"consider_pct": 0.90, "strong_pct": 0.95, "elite_pct": 0.975},
            },
        ),
        StrategyConfig(
            name="production_edge_b12",
            probability_shrink_factor=0.75,
            ranking_mode="edge",
            selection_mode="edge",
            min_recommendation="pass",
            min_ev=0.0,
            min_final_confidence=0.02,
            max_history_staleness_days=21,
            min_recency_factor=0.80,
            max_plays_per_player=1,
            max_plays_per_game=2,
            max_plays_per_script_cluster=2,
            max_pts_plays=8,
            max_trb_plays=2,
            max_ast_plays=2,
            max_total_plays=10,
            min_board_plays=8,
            non_pts_min_gap_percentile=0.0,
            min_bet_win_rate=0.49,
            medium_bet_win_rate=0.52,
            full_bet_win_rate=0.56,
            medium_tier_percentile=0.0,
            strong_tier_percentile=0.0,
            elite_tier_percentile=0.0,
            sizing_method="tiered_probability",
            base_bet_fraction=0.010,
            small_bet_fraction=0.005,
            medium_bet_fraction=0.010,
            full_bet_fraction=0.015,
            max_bet_fraction=0.02,
            max_total_bet_fraction=0.06,
            edge_scale_start_percentile=0.75,
            edge_scale_span=0.25,
            edge_scale_lift=0.15,
            edge_scale_max_multiplier=1.25,
            target_thresholds={
                "PTS": {"consider_pct": 0.80, "strong_pct": 0.90, "elite_pct": 0.95},
                "TRB": {"consider_pct": 0.90, "strong_pct": 0.95, "elite_pct": 0.975},
                "AST": {"consider_pct": 0.90, "strong_pct": 0.95, "elite_pct": 0.975},
            },
        ),
        StrategyConfig(
            name="production_abs_edge_b12",
            probability_shrink_factor=0.75,
            ranking_mode="abs_edge",
            selection_mode="abs_edge",
            min_recommendation="pass",
            min_ev=0.0,
            min_final_confidence=0.02,
            max_history_staleness_days=21,
            min_recency_factor=0.80,
            max_plays_per_player=1,
            max_plays_per_game=2,
            max_plays_per_script_cluster=2,
            max_pts_plays=8,
            max_trb_plays=2,
            max_ast_plays=2,
            max_total_plays=10,
            min_board_plays=8,
            non_pts_min_gap_percentile=0.0,
            min_bet_win_rate=0.49,
            medium_bet_win_rate=0.52,
            full_bet_win_rate=0.56,
            medium_tier_percentile=0.0,
            strong_tier_percentile=0.0,
            elite_tier_percentile=0.0,
            sizing_method="tiered_probability",
            base_bet_fraction=0.010,
            small_bet_fraction=0.005,
            medium_bet_fraction=0.010,
            full_bet_fraction=0.015,
            max_bet_fraction=0.02,
            max_total_bet_fraction=0.06,
            edge_scale_start_percentile=0.75,
            edge_scale_span=0.25,
            edge_scale_lift=0.15,
            edge_scale_max_multiplier=1.25,
            target_thresholds={
                "PTS": {"consider_pct": 0.80, "strong_pct": 0.90, "elite_pct": 0.95},
                "TRB": {"consider_pct": 0.90, "strong_pct": 0.95, "elite_pct": 0.975},
                "AST": {"consider_pct": 0.90, "strong_pct": 0.95, "elite_pct": 0.975},
            },
        ),
        StrategyConfig(
            name="production_high_precision",
            probability_shrink_factor=0.75,
            ranking_mode="ev_adjusted",
            min_ev=0.05,
            min_final_confidence=0.06,
            max_history_staleness_days=14,
            min_recency_factor=0.88,
            min_recommendation="consider",
            max_plays_per_player=1,
            max_pts_plays=4,
            max_trb_plays=2,
            max_ast_plays=2,
            max_total_plays=4,
            non_pts_min_gap_percentile=0.95,
            sizing_method="tiered_probability",
            base_bet_fraction=0.010,
            small_bet_fraction=0.005,
            medium_bet_fraction=0.010,
            full_bet_fraction=0.015,
            max_bet_fraction=0.0175,
            max_total_bet_fraction=0.05,
            edge_scale_start_percentile=0.75,
            edge_scale_span=0.25,
            edge_scale_lift=0.12,
            edge_scale_max_multiplier=1.20,
            target_thresholds={
                "PTS": {"consider_pct": 0.80, "strong_pct": 0.90, "elite_pct": 0.95},
                "TRB": {"consider_pct": 0.90, "strong_pct": 0.95, "elite_pct": 0.975},
                "AST": {"consider_pct": 0.90, "strong_pct": 0.95, "elite_pct": 0.975},
            },
        ),
        StrategyConfig(
            name="production_selective_rejector",
            probability_shrink_factor=0.75,
            ranking_mode="ev_adjusted",
            accept_reject_enabled=True,
            accept_reject_min_train_rows=3000,
            accept_reject_holdout_days=45,
            accept_reject_min_holdout_rows=250,
            accept_reject_min_accept_rate=0.05,
            accept_reject_threshold_floor=0.70,
            min_ev=0.05,
            min_final_confidence=0.03,
            min_recommendation="consider",
            max_plays_per_player=1,
            max_pts_plays=6,
            max_trb_plays=2,
            max_ast_plays=2,
            max_total_plays=10,
            non_pts_min_gap_percentile=0.90,
            sizing_method="tiered_probability",
            base_bet_fraction=0.010,
            small_bet_fraction=0.005,
            medium_bet_fraction=0.010,
            full_bet_fraction=0.015,
            max_bet_fraction=0.02,
            max_total_bet_fraction=0.06,
            edge_scale_start_percentile=0.75,
            edge_scale_span=0.25,
            edge_scale_lift=0.15,
            edge_scale_max_multiplier=1.25,
            target_thresholds={
                "PTS": {"consider_pct": 0.80, "strong_pct": 0.90, "elite_pct": 0.95},
                "TRB": {"consider_pct": 0.90, "strong_pct": 0.95, "elite_pct": 0.975},
                "AST": {"consider_pct": 0.90, "strong_pct": 0.95, "elite_pct": 0.975},
            },
        ),
        StrategyConfig(
            name="production_selective_balanced",
            probability_shrink_factor=0.75,
            ranking_mode="ev_adjusted",
            accept_reject_enabled=True,
            accept_reject_min_train_rows=3000,
            accept_reject_holdout_days=45,
            accept_reject_min_holdout_rows=250,
            accept_reject_min_accept_rate=0.05,
            accept_reject_threshold_floor=0.685,
            min_ev=0.05,
            min_final_confidence=0.04,
            min_recommendation="consider",
            max_plays_per_player=1,
            max_pts_plays=6,
            max_trb_plays=2,
            max_ast_plays=2,
            max_total_plays=6,
            non_pts_min_gap_percentile=0.90,
            sizing_method="tiered_probability",
            base_bet_fraction=0.010,
            small_bet_fraction=0.005,
            medium_bet_fraction=0.010,
            full_bet_fraction=0.015,
            max_bet_fraction=0.02,
            max_total_bet_fraction=0.06,
            edge_scale_start_percentile=0.75,
            edge_scale_span=0.25,
            edge_scale_lift=0.15,
            edge_scale_max_multiplier=1.25,
            target_thresholds={
                "PTS": {"consider_pct": 0.80, "strong_pct": 0.90, "elite_pct": 0.95},
                "TRB": {"consider_pct": 0.90, "strong_pct": 0.95, "elite_pct": 0.975},
                "AST": {"consider_pct": 0.90, "strong_pct": 0.95, "elite_pct": 0.975},
            },
        ),
        StrategyConfig(
            name="production_selective_robust_reranker",
            probability_shrink_factor=0.75,
            ranking_mode="robust_reranker",
            robust_reranker_min_train_rows=4000,
            robust_reranker_holdout_days=45,
            robust_reranker_min_holdout_rows=250,
            robust_reranker_num_pair_per_sample=12,
            robust_reranker_min_candidate_win_rate=0.55,
            robust_reranker_min_candidate_final_confidence=0.04,
            robust_reranker_min_candidate_recommendation="consider",
            accept_reject_enabled=True,
            accept_reject_min_train_rows=3000,
            accept_reject_holdout_days=45,
            accept_reject_min_holdout_rows=250,
            accept_reject_min_accept_rate=0.05,
            accept_reject_threshold_floor=0.685,
            min_ev=0.05,
            min_final_confidence=0.04,
            min_recommendation="consider",
            max_plays_per_player=1,
            max_pts_plays=6,
            max_trb_plays=2,
            max_ast_plays=2,
            max_total_plays=6,
            non_pts_min_gap_percentile=0.90,
            sizing_method="tiered_probability",
            base_bet_fraction=0.010,
            small_bet_fraction=0.005,
            medium_bet_fraction=0.010,
            full_bet_fraction=0.015,
            max_bet_fraction=0.02,
            max_total_bet_fraction=0.06,
            edge_scale_start_percentile=0.75,
            edge_scale_span=0.25,
            edge_scale_lift=0.15,
            edge_scale_max_multiplier=1.25,
            target_thresholds={
                "PTS": {"consider_pct": 0.80, "strong_pct": 0.90, "elite_pct": 0.95},
                "TRB": {"consider_pct": 0.90, "strong_pct": 0.95, "elite_pct": 0.975},
                "AST": {"consider_pct": 0.90, "strong_pct": 0.95, "elite_pct": 0.975},
            },
        ),
        StrategyConfig(
            name="holdout_xgb_ltr",
            probability_shrink_factor=0.75,
            ranking_mode="xgb_ltr",
            xgb_ltr_min_train_rows=4000,
            xgb_ltr_num_pair_per_sample=12,
            min_ev=0.05,
            min_final_confidence=0.03,
            min_recommendation="consider",
            max_plays_per_player=1,
            max_pts_plays=6,
            max_trb_plays=2,
            max_ast_plays=2,
            max_total_plays=10,
            non_pts_min_gap_percentile=0.90,
            sizing_method="tiered_probability",
            base_bet_fraction=0.010,
            small_bet_fraction=0.005,
            medium_bet_fraction=0.010,
            full_bet_fraction=0.015,
            max_bet_fraction=0.02,
            max_total_bet_fraction=0.06,
            edge_scale_start_percentile=0.75,
            edge_scale_span=0.25,
            edge_scale_lift=0.15,
            edge_scale_max_multiplier=1.25,
            target_thresholds={
                "PTS": {"consider_pct": 0.80, "strong_pct": 0.90, "elite_pct": 0.95},
                "TRB": {"consider_pct": 0.90, "strong_pct": 0.95, "elite_pct": 0.975},
                "AST": {"consider_pct": 0.90, "strong_pct": 0.95, "elite_pct": 0.975},
            },
        ),
        StrategyConfig(
            name="strict_current_plus",
            probability_shrink_factor=0.75,
            ranking_mode="ev_adjusted",
            min_ev=0.01,
            min_final_confidence=0.04,
            max_pts_plays=5,
            max_trb_plays=3,
            max_ast_plays=2,
            max_total_plays=8,
            non_pts_min_gap_percentile=0.93,
            kelly_fraction=0.20,
            max_bet_fraction=0.04,
        ),
        StrategyConfig(
            name="balanced_current",
            probability_shrink_factor=0.75,
            ranking_mode="ev_adjusted",
            min_ev=0.0,
            min_final_confidence=0.03,
            max_pts_plays=6,
            max_trb_plays=4,
            max_ast_plays=2,
            max_total_plays=12,
            non_pts_min_gap_percentile=0.90,
            kelly_fraction=0.25,
            max_bet_fraction=0.05,
        ),
        StrategyConfig(
            name="aggressive_shadow",
            probability_shrink_factor=0.75,
            ranking_mode="edge",
            selection_mode="edge",
            min_recommendation="pass",
            min_ev=-0.20,
            min_final_confidence=0.0,
            max_plays_per_game=0,
            max_pts_plays=8,
            max_trb_plays=5,
            max_ast_plays=3,
            max_total_plays=8,
            non_pts_min_gap_percentile=0.0,
            min_bet_win_rate=0.50,
            medium_bet_win_rate=0.54,
            full_bet_win_rate=0.58,
            kelly_fraction=0.35,
            max_bet_fraction=0.06,
        ),
        StrategyConfig(
            name="shadow_edge_append_agree3_p90",
            probability_shrink_factor=0.75,
            ranking_mode="edge_append_shadow",
            selection_mode="edge_append_shadow",
            min_recommendation="pass",
            min_ev=-0.20,
            min_final_confidence=0.0,
            max_plays_per_game=0,
            max_plays_per_script_cluster=3,
            max_pts_plays=10,
            max_trb_plays=4,
            max_ast_plays=4,
            max_total_plays=12,
            non_pts_min_gap_percentile=0.0,
            min_bet_win_rate=0.49,
            medium_bet_win_rate=0.52,
            full_bet_win_rate=0.56,
            medium_tier_percentile=0.0,
            strong_tier_percentile=0.0,
            elite_tier_percentile=0.0,
            append_agreement_min=3,
            append_edge_percentile_min=0.90,
            append_max_extra_plays=3,
            kelly_fraction=0.35,
            max_bet_fraction=0.06,
        ),
        StrategyConfig(
            name="shadow_edge_append_agree1_p90_x1",
            probability_shrink_factor=0.75,
            ranking_mode="edge_append_shadow",
            selection_mode="edge_append_shadow",
            min_recommendation="pass",
            min_ev=-0.20,
            min_final_confidence=0.0,
            max_plays_per_game=0,
            max_plays_per_script_cluster=3,
            max_pts_plays=10,
            max_trb_plays=4,
            max_ast_plays=4,
            max_total_plays=12,
            non_pts_min_gap_percentile=0.0,
            min_bet_win_rate=0.49,
            medium_bet_win_rate=0.52,
            full_bet_win_rate=0.56,
            medium_tier_percentile=0.0,
            strong_tier_percentile=0.0,
            elite_tier_percentile=0.0,
            append_agreement_min=1,
            append_edge_percentile_min=0.90,
            append_max_extra_plays=1,
            kelly_fraction=0.35,
            max_bet_fraction=0.06,
        ),
        StrategyConfig(
            name="shadow_edge_append_agree3_p95",
            probability_shrink_factor=0.75,
            ranking_mode="edge_append_shadow",
            selection_mode="edge_append_shadow",
            min_recommendation="pass",
            min_ev=-0.20,
            min_final_confidence=0.0,
            max_plays_per_game=0,
            max_plays_per_script_cluster=3,
            max_pts_plays=10,
            max_trb_plays=4,
            max_ast_plays=4,
            max_total_plays=12,
            non_pts_min_gap_percentile=0.0,
            min_bet_win_rate=0.49,
            medium_bet_win_rate=0.52,
            full_bet_win_rate=0.56,
            medium_tier_percentile=0.0,
            strong_tier_percentile=0.0,
            elite_tier_percentile=0.0,
            append_agreement_min=3,
            append_edge_percentile_min=0.95,
            append_max_extra_plays=3,
            kelly_fraction=0.35,
            max_bet_fraction=0.06,
        ),
    ]


def build_grid_strategies(
    min_final_confidences: Iterable[float],
    min_evs: Iterable[float],
    max_total_plays: Iterable[int],
    non_pts_percentiles: Iterable[float],
    kelly_fractions: Iterable[float],
    base_config: StrategyConfig | None = None,
) -> list[StrategyConfig]:
    base = base_config or StrategyConfig(name="grid_base")
    configs: list[StrategyConfig] = []
    for idx, (min_conf, min_ev, max_total, non_pts_pct, kelly_fraction) in enumerate(
        product(min_final_confidences, min_evs, max_total_plays, non_pts_percentiles, kelly_fractions),
        start=1,
    ):
        payload = base.to_dict()
        payload.update(
            {
                "name": f"grid_{idx:03d}",
                "min_final_confidence": float(min_conf),
                "min_ev": float(min_ev),
                "max_total_plays": int(max_total),
                "non_pts_min_gap_percentile": float(non_pts_pct),
                "kelly_fraction": float(kelly_fraction),
            }
        )
        configs.append(StrategyConfig(**payload))
    return configs


def summarize_results(results: list[SimulationResult]) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    for result in results:
        overall = result.summary["overall"]
        selected = result.summary["gating_effectiveness"]["selected_candidates"]
        expected_profit = overall["expected_profit"]
        total_profit = overall["total_profit"]
        rows.append(
            {
                "strategy": result.config.name,
                "total_profit": total_profit,
                "ending_bankroll": overall["ending_bankroll"],
                "roi": overall["roi"],
                "profit_per_opportunity": overall["profit_per_opportunity"],
                "log_bankroll_growth": overall["log_bankroll_growth"],
                "max_drawdown": overall["max_drawdown"],
                "selected_plays": overall["selected_plays"],
                "selected_win_rate": selected["win_rate"],
                "gated_opportunities": overall["gated_opportunities"],
                "opportunities": overall["opportunities"],
                "expected_profit": expected_profit,
                "ev_capture_ratio": (total_profit / expected_profit) if expected_profit else None,
                "ev_realization_gap": overall["ev_realization_gap"],
            }
        )
    return pd.DataFrame.from_records(rows)


def run_policy_tuning(
    data: str | pd.DataFrame,
    configs: list[StrategyConfig],
    objective: str = "ending_bankroll",
) -> tuple[list[SimulationResult], pd.DataFrame]:
    results = [simulate_strategy(data, config) for config in configs]
    summary_df = summarize_results(results)
    if not summary_df.empty and objective in summary_df.columns:
        summary_df = summary_df.sort_values([objective, "total_profit"], ascending=[False, False]).reset_index(drop=True)
    return results, summary_df
